name: 'Monorepo Split'

on:
    push:
        branches:
            - main
        tags:
            - '*'

jobs:
    build-matrix:
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/checkout@v4
            -   uses: shivammathur/setup-php@2.25.5
                with:
                    php-version: 8.3
                    ini-values: "memory_limit=-1, error_reporting=-1, display_errors=On"
            -   name: Install dependencies
                uses: ramsey/composer-install@2.2.0
            -   id: set-packages
                run: echo "packages=$(ls packages | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
        outputs:
            packages: ${{ steps.set-packages.outputs.packages }}

    split:
        needs: build-matrix
        runs-on: ubuntu-22.04
        strategy:
            fail-fast: false
            matrix:
                package: ${{ fromJson(needs.build-matrix.outputs.packages) }}
        steps:
            -   uses: actions/checkout@v4
            -   if: "!startsWith(github.ref, 'refs/tags/')"
                uses: symplify/monorepo-split-github-action@2.4
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package_directory: 'packages/${{ matrix.package }}'
                    repository_organization: 'dlakomski'
                    repository_name: '${{ matrix.package }}'
                    user_email: dawid.lakomski@gmail.com
                    user_name: dlakomski
                    branch: main
            -   if: "startsWith(github.ref, 'refs/tags/')"
                uses: symplify/monorepo-split-github-action@2.4
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    tag: ${GITHUB_REF#refs/tags/}
                    package_directory: 'packages/${{ matrix.package }}'
                    repository_organization: 'dlakomski'
                    repository_name: '${{ matrix.package }}'
                    user_email: dawid.lakomski@gmail.com
                    user_name: dlakomski
                    branch: main
